name: Build Container

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.*/**'
      - 'renovate.json'
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract commit details
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:v1.0.${{ github.run_number }}
            ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64
